module.exports = {
  generates: {
    "./src/types/generated.ts": {
      schema: [
        {
          name: "lens-graphql-api",
          "https://api-mumbai.lens.dev": {},
        },
      ],
      plugins: ["typescript", "typescript-operations"],
      documents: ["./src/**/*.graphql"],
    },
  },
  config: {
    maybeValue: "T | undefined",
    skipTypename: true,
    enumsAsTypes: true,
    allowEnumStringTypes: true,
    omitOperationSuffix: true,
    onlyOperationTypes: true,
    declarationKind: "interface",
    namingConvention: {
      enumValues: "keep",
      typeNames: "keep",
    },
    scalars: {
      BigDecimal: "number | string",
      Date: "string",
      DateTime: "string",
      ErrorPath: "string",
      ISO8601Date: "string",
      ISO8601DateTime: "string",
      JSON: "string | Record<any, any>",
      OverflowDate: "string | number",
      RecurrenceInterval: "string | number | Array<string | number>",
      RecurrenceOn: "string",
      Time: "string",
      _Any: "any",
      BlockchainData: "string",
      BroadcastId: "string",
      ChainId: "string",
      CollectModuleData: "string",
      ContractAddress: "string",
      CreateHandle: "string",
      Cursor: "string",
      DateTime: "string",
      Ens: "string",
      EthereumAddress: "string",
      FollowModuleData: "string",
      Handle: "string",
      HandleClaimIdScalar: "string",
      InternalPublicationId: "string",
      Jwt: "string",
      LimitScalar: "string",
      Markdown: "string",
      MimeType: "string",
      NftOwnershipId: "string",
      Nonce: "string",
      ProfileId: "string",
      PublicationId: "string",
      PublicationUrl: "string",
      ReferenceModuleData: "string",
      Search: "string",
      Signature: "string",
      Sources: "string",
      TimestampScalar: "string",
      TxHash: "string",
      TxId: "string",
      UnixTimestamp: "string",
      Url: "string",
      Void: "string",
    },
  },
};
