import type { NextComponentType } from "next";
import Head from "next/head";

export const Header: NextComponentType = () => {
  return (
    <Head>
      <title>Decentralized Onboarding</title>
      <meta
        name="Decentralized onboarding with lens"
        content="Generated by @rainbow-me/create-rainbowkit, @castlelinkhq"
      />
      <link rel="icon" />
    </Head>
  );
};
